project:
  type: website

website:
  title: "mahanirvana"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Introduction"
        menu:
          - href: content/k-intro/dedication.qmd
            text: Dedication
          - href: content/k-intro/source-material.qmd
            text: Source Material
          - href: content/k-intro/why-yamt.qmd
            text: Why YAMT

book:
  chapters:
    - index.qmd
    - part: "Introductory Sections"
      chapters:
        - content/k-intro/dedication.qmd
        - content/k-intro/source-material.qmd
        - content/k-intro/why-yamt.qmd
    # - part: "Main Text"
    #   chapters:
    #     - content/chapter1/assembled.qmd
    #     - content/chapter2/assembled.qmd # Add more as you go

format:
  html:
    theme:
      - materia
      - styles/brand.scss
    css: styles/styles.css
    toc: true
