project:
  type: website

website:
  title: "mahanirvana"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Introduction"
        menu:
          - href: dedication
            text: Dedication
          - href: source-material
            text: Source Material
          - href: why-yamt
            text: Why YAMT

format:
  html:
    theme:
      - materia
    css: styles/styles.css
    toc: true
