project:
  type: website

website:
  title: "mahanirvana"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Introduction"
        menu:
          - href: content/k-intro/dedication.qmd
            text: Dedication
          - href: content/k-intro/source-material.qmd
            text: Source Material
          - href: content/k-intro/why-yamt.qmd
            text: Why YAMT

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
