name: Quarto Publish

on:
  workflow_dispatch: # Enables manual trigger from GitHub UI

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Prevent unauthorized users
        if: github.actor != 'ramnathk'
        run: |
          echo "🚫 Unauthorized: ${{ github.actor }} is not allowed to run this workflow."
          exit 1

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install dependencies
        run: |
          sudo apt-get update

      - name: Render Quarto site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
